[package]
name = "compress"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5.1", features = ["json"]}
dotenv = "0.15.0"
serde = {version = "1.0.215", features = ["derive"]}
diesel = { version = "2.2.5", features = ["sqlite"] }
